# Generated by Django 4.0.1 on 2022-04-30 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_recentwork'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, verbose_name='Project title')),
                ('image', models.ImageField(upload_to='projects')),
            ],
        ),
        migrations.DeleteModel(
            name='RecentWork',
        ),
    ]
