# Generated by Django 4.0.1 on 2022-04-30 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_project_delete_recentwork'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
