# Generated by Django 4.0.1 on 2022-05-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_delete_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='static/img/')),
                ('code', models.TextField()),
            ],
        ),
    ]
