# Generated by Django 4.0.1 on 2022-05-01 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
    ]
